# Site settings
title: Seif Haddad
email: seifhaddad45@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seifhaddad.github.io" # the base hostname & protocol for your site
facebook_username: seifhaddad
# twitter_username: jekyllrb
github_username:  seifhaddad

# Build settings
markdown: kramdown
